name: altrepo-api

services:
  app:
    environment:
      - TZ=Europe/Moscow
    build: .
    restart: unless-stopped
    command: ./run-api /config/api.conf
    volumes:
      - ${PWD}/api.conf.docker:/config/api.conf
      - log:/log
    ports:
      - ${APP_PORT_EXT}:5000
    logging:
      options:
        tag: ${APP_LOGGING_TAG}
volumes:
  config:
  log:
